#
# Configuration for the Lustre HSM Action Shipper
#

# --- 1. Redis Connection ---
# You MUST edit 'redis_host' to point to your Redis server.
redis_host: "localhost"
redis_port: 6379

# The Redis database number to use. This must be an integer within the
# range configured on your Redis server (default is 0-15).
# Ensure this database is not used by another application.
redis_db: 1

# The PREFIX for the Redis Streams. The shipper will append the MDT name
# to this prefix to create a stream per MDT.
# Example: hsm:actions:lustre-MDT0000, hsm:actions:lustre-MDT0001, etc.
redis_stream_prefix: "hsm:actions"

# --- 2. Action File Polling ---
# Glob pattern to find Lustre HSM action files.
# This default glob will automatically find any Lustre filesystem on the MDS.
mdt_watch_glob: "/sys/kernel/debug/lustre/mdt/*-MDT????/hsm/actions"

# How often to poll the actions files, in seconds. This should be less
# than half of the 'hsm/grace_delay' setting in Lustre (default 60s).
poll_interval: 20.0

# --- 3. Maintenance and Trimming ---
# How often (in seconds) the shipper should run its internal maintenance task.
reconcile_interval: 21600 # 6 hours

# When trimming large backlogs of historical events, the operation is done
# in chunks to avoid blocking Redis. This sets the size of each chunk.
trim_chunk_size: 1000

# Use Redis's approximate trimming (~). This is faster but may require
# multiple passes to trim everything older than the target ID.
# Recommended: true (for production), false (for deterministic testing).
use_approximate_trimming: true


# --- 4. Cache and Logging ---
# Path to a file where the shipper will cache the last seen state of action files.
# This prevents re-shipping events on restart.
cache_path: "/var/cache/hsm-action-shipper/cache.json"

# Log level. Can be DEBUG, INFO, WARNING, ERROR, CRITICAL.
log_level: "INFO"

# Path to the log file. If commented out, logs to standard output.
# log_file: "/var/log/hsm_action_shipper.log"
