#
# Configuration for the hsm-stream-janitor service.
#

# --- Redis Connection (REQUIRED) ---
# These details MUST match the shipper's configuration.
redis_host: "localhost"
redis_port: 6379
redis_db: 1
redis_stream_name: "hsm:actions"

# --- Operation Interval ---
# How often the janitor will analyze the stream and perform a cleanup, in seconds.
operation_interval_seconds: 120

# --- Self-Healing Timeout ---
# How long to wait before forcefully removing an action for which NO event
# (including a heartbeat) has been seen. This is a safety net for "stale"
# actions where a PURGED event was missed.
# This value should be safely longer than the shipper's 'heartbeat_interval'.
stale_action_timeout_seconds: 86400 # 24 hours

# --- Logging ---
log_level: "INFO"
