#
# Configuration for the hsm-action-shipper service.
#

# --- 1. Redis Connection (REQUIRED) ---
# You MUST edit 'redis_host' to point to your Redis server.
redis_host: "localhost"
redis_port: 6379

# The Redis database number to use. This must be an integer within the
# range configured on your Redis server (default is 0-15).
# Ensure this database is not used by another application.
redis_db: 1

# The PREFIX for the Redis Streams. The shipper will append the MDT name
# to this prefix to create a stream per MDT.
# Example: hsm:actions:elm-MDT0000, hsm:actions:elm-MDT0001, etc.
redis_stream_prefix: "hsm:actions"

# --- 2. Filesystem Polling ---
# This default glob will automatically find any Lustre filesystem on the MDS.
mdt_watch_glob: "/sys/kernel/debug/lustre/mdt/*-MDT*/hsm/actions"

# How often to poll the actions files, in seconds. This should be less
# than half of the 'hsm/grace_delay' setting in Lustre (default 60s).
poll_interval: 20

# --- 3. Maintenance and Trimming ---
# How often the shipper should run its internal maintenance task. This task
# validates stream consistency and trims old events.
reconcile_interval: 21600 # 6 hours

# Redis limits how many entries can be trimmed at once (usually up to 10k).
# This can be problematic for large backlogs.
# If the maintenance task trims more than aggressive_trim_threshold entries
# from a stream in one pass, it will immediately run the trim operation again
# or that stream to efficiently clear large backlogs.
aggressive_trim_threshold: 5000

# --- 4. Cache and Logging ---
# The file to store the shipper's persistent action cache.
cache_path: "/var/cache/hsm-action-shipper/cache.json"

# Log level can be DEBUG, INFO, WARNING, ERROR, CRITICAL.
log_level: "INFO"
