#
# Configuration for the hsm-stream-janitor service.
#

# --- Redis Connection (REQUIRED) ---
# These details MUST match the shipper's configuration.
redis_host: "localhost"
redis_port: 6379
redis_db: 1
redis_stream_name: "hsm:actions"

# The name of the main Redis Stream.
redis_stream_name: "hsm:actions"

# Must match the shipper's heartbeat stream name.
redis_heartbeat_stream_name: "hsm:actions:heartbeats"

# --- Operation Interval & Tuning ---
# The *maximum* sleep time between cleanup cycles, in seconds.
operation_interval_seconds: 120

# If the janitor trims more than this many entries from the main stream
# in one cycle, it will immediately run again instead of sleeping.
aggressive_trim_threshold: 5000

# The maximum number of entries to keep in the heartbeat stream.
# This prevents the heartbeat stream from growing indefinitely.
heartbeat_stream_maxlen: 1000000

# --- Self-Healing Timeout ---
# How long to wait before forcefully removing an action for which NO event
# (including a heartbeat) has been seen. This is a safety net for "stale"
# actions where a PURGED event was missed.
# This value should be safely longer than the shipper's 'heartbeat_interval'.
stale_action_timeout_seconds: 86400 # 24 hours

# --- Logging ---
log_level: "INFO"
