name: Lustre HSM Action Stream CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    # This 'services' block starts a Redis container that is accessible
    # to the steps in this job at localhost:6379. This is our test database.
    services:
      redis:
        image: redis:6
        # Options to wait for Redis to be healthy before starting the test steps.
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies (Redis client)
        run: |
          sudo apt-get update

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Install the project and its runtime dependencies (PyYAML, redis)
          pip install -e .
          # Install the dependencies required for testing
          pip install pytest pytest-cov

      - name: Run Pytest suite with code coverage
        run: |
          # This single command runs our entire, unified pytest suite.
          # - PYTHONPATH=src is needed so Python can find the application modules.
          # - -v provides verbose output, showing each test that runs.
          # - --cov generates a code coverage report for our application package.
          PYTHONPATH=src pytest -v --cov=lustre_hsm_action_stream --cov-report=term-missing
